modified script to run recorder first

diff --git a/samples/compress_samples b/samples/compress_samples
--- a/samples/compress_samples
+++ b/samples/compress_samples
@@ -30,12 +30,19 @@ echo "Done."
 echo "-------------------------------------------------------"    
 }
 
-if [ "$#" -ne 1 ]; then
-    usage
+# if [ "$#" -ne 1 ]; then
+#     usage
+#     exit 1
+# fi
+
+if ./recorder; then
+    echo "Successfully collected sample! Processing now."
+else
+    echo "Recording process failed!"
     exit 1
 fi
 
-FILE=$1
+FILE="output.ogg"
 
 if [[ ! "$FILE" == *.ogg ]]; then
     echo "Error: Input file is not a .ogg"
